# @package _global_

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

# Directory for project output files
project_dir: "./output"

# Directory containing scenario files
scenario_dir: "./scenarios"

# Random seed for reproducibility
seed: 123

# Automatically select the device (CPU/GPU)
device: "auto"

# Set to false to disable debug output
debug_mode: false

# Dataset generation options
dataset:
  # Number of episodes to collect for the dataset
  num_episodes: 1000
  # Number of episodes per batch
  batch_size: 32
  # Number of timesteps for observation
  t_obs: 10
  # Number of timesteps for prediction
  t_pred: 10
  # Number of processes for dataset generation
  num_workers: 1

wandb:
  # Enable Weights & Biases logging
  enabled: true
  # Project name for Weights & Biases
  project: PredictiveStateRepresentations-AD

representation:
  model_path: "./models/checkpoint.pth"

# Training configuration
training:
  # Type of model to use for training
  model_type: "PredictiveModelV8"
  # Latent representation size
  hidden_dim: 64
  # Number of training epochs
  epochs: 1000
  # Batch size for training
  batch_size: 1
  # Learning rate for the optimizer
  learning_rate: 0.001
  # Weight decay for the optimizer
  weight_decay: 0.00001
  # Factor to downsample input images
  downsample_factor: 1
  # Maximum gradient norm for gradient clipping
  max_grad_norm: 1.0
  # Training set split size
  train_ratio: 0.9
  # Number of processes for fetching data in dataloader
  num_workers: 8
  # Whether to use pinned host memory for faster data copies
  pin_memory: true
  # Prefetch factor for dataloader. This is the number of batches to load in advance. Higher values can speed up training.
  prefetch_factor: 2
  # Whether to plot predictions during training
  create_plots: true
  # Whether to log training metrics to stdout
  stdout_logging: true
  # Interval for saving model checkpoints
  save_interval: 10
  # Whether to overwrite existing model checkpoints
  overwrite_checkpoints: true

# Reinforcement Learning Training options
rl_training:
  # Path to save trained models
  save_path: "./rl/models"
  # Path to save training logs
  log_path: "./rl/logs"
  # Frequency of evaluation during training
  eval_freq: 20000
  # Frequency of video recording (in steps)
  video_freq: 20000  
  # Length of each video (in steps)
  video_length: 500 
  # Folder to save videos (relative to project_dir)
  video_folder: "./rl/videos"  
  # Number of parallel environments for training
  num_envs: 16
  # Total number of timesteps for training
  total_timesteps: 1000000
  # Learning rate for the optimizer
  learning_rate: 3e-4
  # Number of steps to collect samples for each update
  n_steps: 256
  # Batch size for each update
  batch_size: 32
  # Number of epochs to train the model
  n_epochs: 8
  # Discount factor for future rewards
  gamma: 0.99
  # Lambda parameter for Generalized Advantage Estimation
  gae_lambda: 0.8
  # Clipping range for the surrogate objective
  clip_range: 0.2
  # Coefficient for the entropy loss
  ent_coef: 0.01
  # Coefficient for the value function loss
  vf_coef: 0.5
  # Maximum norm for gradient clipping
  max_grad_norm: 10.0

# Simulation options
simulation:
  # Steps for lanelet graph conversion (if any)
  lanelet_graph_conversion_steps: null
  # Use linear projection for lanelets
  linear_lanelet_projection: true
  # Whether to sort lanelet assignments
  sort_lanelet_assignments: false

# Control space options
control_space:
  # Minimum acceleration
  lower_bound_acceleration: -6.0
  # Maximum acceleration
  upper_bound_acceleration: 6.5
  # Minimum velocity
  lower_bound_velocity: 0.001
  # Minimum steering angle
  lower_bound_steering: -0.15
  # Maximum steering angle
  upper_bound_steering: 0.15
  # Minimum velocity for steering
  min_velocity_steering: 1.0

# Viewer options
viewer:
  # Range of view in the simulation
  view_range: 110.0
  # Size of the viewer window
  window_size: 64

# Respawner options
respawner:
  # Randomize initial arclength
  random_init_arclength: true
  # Randomize goal arclength
  random_goal_arclength: true
  # Randomize start timestep
  random_start_timestep: true
  # Spawn only at intersections
  only_intersections: false
  # Min and max route length
  route_length: [10, 15]
  # Initial speed distribution
  init_speed: "uniform_random"
  # Minimum initial arclength
  min_init_arclength: 100.0
  # Range for random speed
  random_speed_range: [0.0, 50.0]
  # Initial steering angle distribution
  init_steering_angle: "uniform_random"
  # Range for random steering angle
  random_steering_angle_range: [-0.08, 0.08]
  # Noise in initial orientation
  init_orientation_noise: 0.4
  # Noise in initial position
  init_position_noise: 3.0
  # Minimum distance to goal
  min_goal_distance: 100.0
  # Minimum L2 distance to goal
  min_goal_distance_l2: 100.0
  # Maximum L2 distance to goal (if any)
  max_goal_distance_l2: null
  # Maximum distance to goal (if any)
  max_goal_distance: null
  # Minimum remaining distance (if any)
  min_remaining_distance: null
  # Maximum outer attempts for respawning
  max_attempts_outer: 50
  # Minimum distance between vehicles
  min_vehicle_distance: 0.0
  # Minimum vehicle speed (if any)
  min_vehicle_speed: null
  # Minimum number of vehicles on route (if any)
  min_vehicles_route: null
  # Maximum inner attempts for respawning
  max_attempts_inner: 5

# Traffic extraction options
traffic_extraction:
  # Type of edge drawer to use
  edge_drawer: "NoEdgeDrawer"
  # List of postprocessors to apply
  postprocessors: []
  # Consider only ego-centric incoming edges
  only_ego_inc_edges: false
  # Assign vehicles to multiple lanelets
  assign_multiple_lanelets: true
  # Radius of ego-centric map
  ego_map_radius: 50.0
  # Include lanelet vertices in extraction
  include_lanelet_vertices: false